import {
  BRACE_COOLDOWN_MS,
  BRACE_DURATION_MS,
  DASH_COOLDOWN_MS,
  DASH_DURATION_MS,
  FLIP_COOLDOWN_MS,
} from "@/lib/battleTuning";
import type { AbilityId, BaseAbilityId } from "./types";
import { ALL_ABILITY_IDS, BASE_ABILITY_IDS } from "./types";

export type AbilityKind = "base" | "active" | "passive";

export interface AbilityDef {
  id: AbilityId;
  /** Ключ в t.loadout.ability */
  nameKey: AbilityId;
  kind: AbilityKind;
  /** Ключ в t.loadout.abilityDesc */
  descriptionKey: AbilityId;
  cooldownMs?: number;
  durationMs?: number;
}

/**
 * Реестр способностей. dash/flip/brace — рабочие в core;
 * остальные — метаданные для UI/драфта/рогалика (геймплей подключается постепенно).
 */
export const ABILITY_DEFS: Record<AbilityId, AbilityDef> = {
  dash: {
    id: "dash",
    nameKey: "dash",
    kind: "base",
    descriptionKey: "dash",
    cooldownMs: DASH_COOLDOWN_MS,
    durationMs: DASH_DURATION_MS,
  },
  flip: {
    id: "flip",
    nameKey: "flip",
    kind: "base",
    descriptionKey: "flip",
    cooldownMs: FLIP_COOLDOWN_MS,
  },
  brace: {
    id: "brace",
    nameKey: "brace",
    kind: "base",
    descriptionKey: "brace",
    cooldownMs: BRACE_COOLDOWN_MS,
    durationMs: BRACE_DURATION_MS,
  },
  shield: {
    id: "shield",
    nameKey: "shield",
    kind: "active",
    descriptionKey: "shield",
    cooldownMs: 12000,
    durationMs: 2000,
  },
  slam: {
    id: "slam",
    nameKey: "slam",
    kind: "active",
    descriptionKey: "slam",
    cooldownMs: 8000,
  },
  magnet: {
    id: "magnet",
    nameKey: "magnet",
    kind: "active",
    descriptionKey: "magnet",
    cooldownMs: 10000,
    durationMs: 1500,
  },
  push: {
    id: "push",
    nameKey: "push",
    kind: "active",
    descriptionKey: "push",
    cooldownMs: 7000,
  },
  vamp: {
    id: "vamp",
    nameKey: "vamp",
    kind: "passive",
    descriptionKey: "vamp",
  },
  giant: {
    id: "giant",
    nameKey: "giant",
    kind: "active",
    descriptionKey: "giant",
    cooldownMs: 20000,
    durationMs: 4000,
  },
  spikes: {
    id: "spikes",
    nameKey: "spikes",
    kind: "passive",
    descriptionKey: "spikes",
  },
  secondWind: {
    id: "secondWind",
    nameKey: "secondWind",
    kind: "passive",
    descriptionKey: "secondWind",
  },
  freezeEnemy: {
    id: "freezeEnemy",
    nameKey: "freezeEnemy",
    kind: "active",
    descriptionKey: "freezeEnemy",
    cooldownMs: 14000,
    durationMs: 1200,
  },
  ghost: {
    id: "ghost",
    nameKey: "ghost",
    kind: "active",
    descriptionKey: "ghost",
    cooldownMs: 16000,
    durationMs: 1800,
  },
  uppercut: {
    id: "uppercut",
    nameKey: "uppercut",
    kind: "active",
    descriptionKey: "uppercut",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  counter: {
    id: "counter",
    nameKey: "counter",
    kind: "active",
    descriptionKey: "counter",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  dodgeRoll: {
    id: "dodgeRoll",
    nameKey: "dodgeRoll",
    kind: "active",
    descriptionKey: "dodgeRoll",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  lasso: {
    id: "lasso",
    nameKey: "lasso",
    kind: "active",
    descriptionKey: "lasso",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  sharePain: {
    id: "sharePain",
    nameKey: "sharePain",
    kind: "passive",
    descriptionKey: "sharePain",
  },
  luckyStrike: {
    id: "luckyStrike",
    nameKey: "luckyStrike",
    kind: "passive",
    descriptionKey: "luckyStrike",
  },
  magnetHands: {
    id: "magnetHands",
    nameKey: "magnetHands",
    kind: "passive",
    descriptionKey: "magnetHands",
  },
  bellyflop: {
    id: "bellyflop",
    nameKey: "bellyflop",
    kind: "active",
    descriptionKey: "bellyflop",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  parry: {
    id: "parry",
    nameKey: "parry",
    kind: "active",
    descriptionKey: "parry",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  doubleJump: {
    id: "doubleJump",
    nameKey: "doubleJump",
    kind: "active",
    descriptionKey: "doubleJump",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  tripwire: {
    id: "tripwire",
    nameKey: "tripwire",
    kind: "active",
    descriptionKey: "tripwire",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  cheer: {
    id: "cheer",
    nameKey: "cheer",
    kind: "active",
    descriptionKey: "cheer",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  banana: {
    id: "banana",
    nameKey: "banana",
    kind: "active",
    descriptionKey: "banana",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  disarmPulse: {
    id: "disarmPulse",
    nameKey: "disarmPulse",
    kind: "active",
    descriptionKey: "disarmPulse",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  headbutt: {
    id: "headbutt",
    nameKey: "headbutt",
    kind: "active",
    descriptionKey: "headbutt",
    cooldownMs: 6000,
    durationMs: 1200,
  },
  turtle: {
    id: "turtle",
    nameKey: "turtle",
    kind: "active",
    descriptionKey: "turtle",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  wallKick: {
    id: "wallKick",
    nameKey: "wallKick",
    kind: "passive",
    descriptionKey: "wallKick",
  },
  stunSlap: {
    id: "stunSlap",
    nameKey: "stunSlap",
    kind: "active",
    descriptionKey: "stunSlap",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  medic: {
    id: "medic",
    nameKey: "medic",
    kind: "active",
    descriptionKey: "medic",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  fart: {
    id: "fart",
    nameKey: "fart",
    kind: "active",
    descriptionKey: "fart",
    cooldownMs: 6000,
    durationMs: 1200,
  },
  weaponYank: {
    id: "weaponYank",
    nameKey: "weaponYank",
    kind: "active",
    descriptionKey: "weaponYank",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  spinKick: {
    id: "spinKick",
    nameKey: "spinKick",
    kind: "active",
    descriptionKey: "spinKick",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  foamArmor: {
    id: "foamArmor",
    nameKey: "foamArmor",
    kind: "passive",
    descriptionKey: "foamArmor",
  },
  slide: {
    id: "slide",
    nameKey: "slide",
    kind: "active",
    descriptionKey: "slide",
    cooldownMs: 6000,
    durationMs: 1200,
  },
  confuse: {
    id: "confuse",
    nameKey: "confuse",
    kind: "active",
    descriptionKey: "confuse",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  guardAlly: {
    id: "guardAlly",
    nameKey: "guardAlly",
    kind: "active",
    descriptionKey: "guardAlly",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  inflatable: {
    id: "inflatable",
    nameKey: "inflatable",
    kind: "active",
    descriptionKey: "inflatable",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  scavenge: {
    id: "scavenge",
    nameKey: "scavenge",
    kind: "passive",
    descriptionKey: "scavenge",
  },
  dropkick: {
    id: "dropkick",
    nameKey: "dropkick",
    kind: "active",
    descriptionKey: "dropkick",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  ironJaw: {
    id: "ironJaw",
    nameKey: "ironJaw",
    kind: "passive",
    descriptionKey: "ironJaw",
  },
  rocketJump: {
    id: "rocketJump",
    nameKey: "rocketJump",
    kind: "active",
    descriptionKey: "rocketJump",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  vacuum: {
    id: "vacuum",
    nameKey: "vacuum",
    kind: "active",
    descriptionKey: "vacuum",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  tagTeam: {
    id: "tagTeam",
    nameKey: "tagTeam",
    kind: "passive",
    descriptionKey: "tagTeam",
  },
  shrink: {
    id: "shrink",
    nameKey: "shrink",
    kind: "active",
    descriptionKey: "shrink",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  timeout: {
    id: "timeout",
    nameKey: "timeout",
    kind: "active",
    descriptionKey: "timeout",
    cooldownMs: 18000,
    durationMs: 3500,
  },
  clothesline: {
    id: "clothesline",
    nameKey: "clothesline",
    kind: "active",
    descriptionKey: "clothesline",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  thickSkin: {
    id: "thickSkin",
    nameKey: "thickSkin",
    kind: "passive",
    descriptionKey: "thickSkin",
  },
  grapple: {
    id: "grapple",
    nameKey: "grapple",
    kind: "active",
    descriptionKey: "grapple",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  repel: {
    id: "repel",
    nameKey: "repel",
    kind: "active",
    descriptionKey: "repel",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  lootSense: {
    id: "lootSense",
    nameKey: "lootSense",
    kind: "passive",
    descriptionKey: "lootSense",
  },
  mirror: {
    id: "mirror",
    nameKey: "mirror",
    kind: "active",
    descriptionKey: "mirror",
    cooldownMs: 18000,
    durationMs: 3500,
  },
  scout: {
    id: "scout",
    nameKey: "scout",
    kind: "passive",
    descriptionKey: "scout",
  },
  suplex: {
    id: "suplex",
    nameKey: "suplex",
    kind: "active",
    descriptionKey: "suplex",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  lastStand: {
    id: "lastStand",
    nameKey: "lastStand",
    kind: "passive",
    descriptionKey: "lastStand",
  },
  teleportSwap: {
    id: "teleportSwap",
    nameKey: "teleportSwap",
    kind: "active",
    descriptionKey: "teleportSwap",
    cooldownMs: 18000,
    durationMs: 3500,
  },
  glue: {
    id: "glue",
    nameKey: "glue",
    kind: "active",
    descriptionKey: "glue",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  rngBomb: {
    id: "rngBomb",
    nameKey: "rngBomb",
    kind: "active",
    descriptionKey: "rngBomb",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  warmup: {
    id: "warmup",
    nameKey: "warmup",
    kind: "passive",
    descriptionKey: "warmup",
  },
  piledriver: {
    id: "piledriver",
    nameKey: "piledriver",
    kind: "active",
    descriptionKey: "piledriver",
    cooldownMs: 18000,
    durationMs: 3500,
  },
  bandage: {
    id: "bandage",
    nameKey: "bandage",
    kind: "active",
    descriptionKey: "bandage",
    cooldownMs: 6000,
    durationMs: 1200,
  },
  blink: {
    id: "blink",
    nameKey: "blink",
    kind: "active",
    descriptionKey: "blink",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  banish: {
    id: "banish",
    nameKey: "banish",
    kind: "active",
    descriptionKey: "banish",
    cooldownMs: 18000,
    durationMs: 3500,
  },
  drunk: {
    id: "drunk",
    nameKey: "drunk",
    kind: "passive",
    descriptionKey: "drunk",
  },
  cooldownCut: {
    id: "cooldownCut",
    nameKey: "cooldownCut",
    kind: "passive",
    descriptionKey: "cooldownCut",
  },
  shoulderCharge: {
    id: "shoulderCharge",
    nameKey: "shoulderCharge",
    kind: "active",
    descriptionKey: "shoulderCharge",
    cooldownMs: 6000,
    durationMs: 1200,
  },
  regen: {
    id: "regen",
    nameKey: "regen",
    kind: "passive",
    descriptionKey: "regen",
  },
  hover: {
    id: "hover",
    nameKey: "hover",
    kind: "active",
    descriptionKey: "hover",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  taunt: {
    id: "taunt",
    nameKey: "taunt",
    kind: "active",
    descriptionKey: "taunt",
    cooldownMs: 6000,
    durationMs: 1200,
  },
  hotPotato: {
    id: "hotPotato",
    nameKey: "hotPotato",
    kind: "active",
    descriptionKey: "hotPotato",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  doubleTap: {
    id: "doubleTap",
    nameKey: "doubleTap",
    kind: "passive",
    descriptionKey: "doubleTap",
  },
  elbowDrop: {
    id: "elbowDrop",
    nameKey: "elbowDrop",
    kind: "active",
    descriptionKey: "elbowDrop",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  adrenaline: {
    id: "adrenaline",
    nameKey: "adrenaline",
    kind: "passive",
    descriptionKey: "adrenaline",
  },
  sprint: {
    id: "sprint",
    nameKey: "sprint",
    kind: "active",
    descriptionKey: "sprint",
    cooldownMs: 6000,
    durationMs: 1200,
  },
  silence: {
    id: "silence",
    nameKey: "silence",
    kind: "active",
    descriptionKey: "silence",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  pirouette: {
    id: "pirouette",
    nameKey: "pirouette",
    kind: "active",
    descriptionKey: "pirouette",
    cooldownMs: 6000,
    durationMs: 1200,
  },
  nullField: {
    id: "nullField",
    nameKey: "nullField",
    kind: "active",
    descriptionKey: "nullField",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  whiplash: {
    id: "whiplash",
    nameKey: "whiplash",
    kind: "active",
    descriptionKey: "whiplash",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  bubble: {
    id: "bubble",
    nameKey: "bubble",
    kind: "active",
    descriptionKey: "bubble",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  moonwalk: {
    id: "moonwalk",
    nameKey: "moonwalk",
    kind: "passive",
    descriptionKey: "moonwalk",
  },
  slowField: {
    id: "slowField",
    nameKey: "slowField",
    kind: "active",
    descriptionKey: "slowField",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  yodel: {
    id: "yodel",
    nameKey: "yodel",
    kind: "active",
    descriptionKey: "yodel",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  overclock: {
    id: "overclock",
    nameKey: "overclock",
    kind: "active",
    descriptionKey: "overclock",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  groundPound: {
    id: "groundPound",
    nameKey: "groundPound",
    kind: "active",
    descriptionKey: "groundPound",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  anchor: {
    id: "anchor",
    nameKey: "anchor",
    kind: "active",
    descriptionKey: "anchor",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  stickyFeet: {
    id: "stickyFeet",
    nameKey: "stickyFeet",
    kind: "passive",
    descriptionKey: "stickyFeet",
  },
  chain: {
    id: "chain",
    nameKey: "chain",
    kind: "passive",
    descriptionKey: "chain",
  },
  rubber: {
    id: "rubber",
    nameKey: "rubber",
    kind: "passive",
    descriptionKey: "rubber",
  },
  echo: {
    id: "echo",
    nameKey: "echo",
    kind: "passive",
    descriptionKey: "echo",
  },
  haymaker: {
    id: "haymaker",
    nameKey: "haymaker",
    kind: "active",
    descriptionKey: "haymaker",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  softLanding: {
    id: "softLanding",
    nameKey: "softLanding",
    kind: "passive",
    descriptionKey: "softLanding",
  },
  jetpack: {
    id: "jetpack",
    nameKey: "jetpack",
    kind: "active",
    descriptionKey: "jetpack",
    cooldownMs: 18000,
    durationMs: 3500,
  },
  mark: {
    id: "mark",
    nameKey: "mark",
    kind: "active",
    descriptionKey: "mark",
    cooldownMs: 8000,
    durationMs: 1500,
  },
  copycat: {
    id: "copycat",
    nameKey: "copycat",
    kind: "passive",
    descriptionKey: "copycat",
  },
  knee: {
    id: "knee",
    nameKey: "knee",
    kind: "active",
    descriptionKey: "knee",
    cooldownMs: 6000,
    durationMs: 1200,
  },
  emergencyExit: {
    id: "emergencyExit",
    nameKey: "emergencyExit",
    kind: "active",
    descriptionKey: "emergencyExit",
    cooldownMs: 14000,
    durationMs: 2500,
  },
  pin: {
    id: "pin",
    nameKey: "pin",
    kind: "active",
    descriptionKey: "pin",
    cooldownMs: 10000,
    durationMs: 2000,
  },
  lowGravity: {
    id: "lowGravity",
    nameKey: "lowGravity",
    kind: "active",
    descriptionKey: "lowGravity",
    cooldownMs: 14000,
    durationMs: 2500,
  },
};

export function getAbilityDef(id: AbilityId): AbilityDef {
  return ABILITY_DEFS[id];
}

/** Способности, которые можно взять в драфте (не база). */
export function draftableAbilityIds(): AbilityId[] {
  return ALL_ABILITY_IDS.filter(
    (id) => !(BASE_ABILITY_IDS as readonly string[]).includes(id),
  );
}

export function isWiredBaseAbility(id: AbilityId): id is BaseAbilityId {
  return (BASE_ABILITY_IDS as readonly string[]).includes(id);
}
